# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

name: Update Release Notes

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  release-notes-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Clone change logs
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          # Need to retrieve the next milestone.
          MILESTONE=v1.14.0

          git clone https://${GITHUB_TOKEN}@github.com/falfaroc/change-log.git
          cd change-log
          git checkout usr/falfaroc/release-notes

          # Update labels for release Notes
          echo '  - area/csi-powermax                                   
            - area/csi-powerstore
            - area/csi-powerflex
            - area/csi-unity
            - area/csi-powerscale
            - area/csm-replication
            - area/csm-resiliency
            - area/csm-authorization
            - area/csm-observability
          #  - area/csm-encryption
          #  - area/csm-application-mobility
            - area/installation-wizard
            - area/csm-operator' >> config.yaml

          make build
          sed -i "s/milestone: \(.*\)*/milestone: \"$MILESTONE\"/g" config.yaml

          # Generate the release notes.
          ./bin/change-log generate

          # Update release notes.
          ./bin/change-log release --changesPath area --directory ../csm-docs

          ls ../

      # # Needed for signing commits using Github App tokens
      # # See: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#commit-signing
      # - name: Generate GitHub App Token
      #   uses: actions/create-github-app-token@v2.0.2
      #   id: generate-token
      #   with:
      #     app-id: ${{ vars.CSM_RELEASE_APP_ID }}
      #     private-key: ${{ secrets.MY_GITHUB_TOKEN }}

      # # Must enable "allow GitHub Actions to create pull requests" setting
      # # Author defaults to the user who triggered the workflow run
      # - name: Create pull request
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     # token: ${{ steps.generate-token.outputs.token }}
      #     branch: "release-notes-update"
      #     commit-message: "Update Release Notes"
      #     title: "Update Release Notes"
      #     body: |
      #       Update release-notes to include features and bug fixes.

      #       Auto-generated by [common-github-actions](https://github.com/dell/common-github-actions)
      #     sign-commits: true
      #     delete-branch: true
